version: "3.8"

services:
  api:
    build: api
    restart: always
    ports:
      - "3000:3000"
    command: 
      - "memory"
      - "db"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
  postgres:
    build: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shorturl
    ports:
      - "5432:5432"
    volumes:
      - ./dataPostgres:/data
  redis:
    build: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./dataRedis:/data